### ISSUE TITLE
pip install not placing skinfer script correctly

### ISSUE THREAD

**Issue by bbotella** [scrapinghub/skinfer#6]
When installing skinfer with pip tool, skinfer script file is not available for users.

Steps to reproduce:
- create your virtual env
- pip install skinfer
- try to execute skinfer

What happens is:
```
user@host:~/$ skinfer
skinfer: command not found
```

When you manually clone the repository, and execute:
```
python setup.py install
```

It works as expected.

**Comment by eliasdorneles** [comment]
Thanks @bbotella -- will look into it soon!

**Comment by eliasdorneles** [comment]
So, this was because the version in PyPI was older, it had the old command `schema_inferer`.

I've just made a new release that fix this: https://github.com/scrapinghub/skinfer/releases/tag/0.2.0
